[pytest]
testpaths = tests
filterwarnings =
    ignore:Using `httpx` with `starlette.testclient` is deprecated:DeprecationWarning
    ignore:Setting the shape on a NumPy array has been deprecated:DeprecationWarning
    ignore::DeprecationWarning:joblib