import { Fragment, forwardRef } from "react";
import clsx from "clsx";

import type { AssessmentResult } from "@/features/assessment/assessmentResult";
import ReportViewer from "./components/ReportViewer";

import styles from "./PrintableReport.module.css";

interface PrintableReportProps {
  assessment: AssessmentResult;
}

/**
 * Off-screen, print-only render of the current assessment.
 *
 * The same <ReportViewer /> used on screen is mounted inside a fixed-width, off-
 * canvas wrapper so recharts' ResponsiveContainer can measure a real width and
 * render the charts. react-to-print clones this node (and the module/global
 * stylesheets) into a hidden iframe, so the printed PDF matches the on-screen
 * report pixel-for-pixel.
 */
const PrintableReport = forwardRef<HTMLDivElement, PrintableReportProps>(
  function PrintableReport({ assessment }, ref) {
    return (
      <div className={styles.screenHost} aria-hidden="true">
        <div ref={ref} className={clsx("report-print-root", styles.root)}>
          <ReportViewer assessment={assessment} disclaimer="short" />
          <Footer assessment={assessment} />
        </div>
      </div>
    );
  },
);

function Footer({ assessment }: { assessment: AssessmentResult }) {
  return (
      <div className={clsx("report-print-footer", styles.footer)}>
        <Fragment>
          Assessment {assessment.id} · Generated by CardioInsight AI Platform
          v1.0.0
        </Fragment>
      </div>
  );
}

export default PrintableReport;