import { useState } from "react";
import { motion, AnimatePresence } from "framer-motion";
import { FileText, Stethoscope, X } from "lucide-react";
import { Link, useNavigate } from "react-router-dom";

import { Button } from "@/components/ui";
import { useAssessment } from "@/features/assessment/useAssessment";
import AssessmentPromo from "@/components/features/assessment/AssessmentPromo";
import { soundService } from "@/services/ui/soundService";
import AssessmentHistory from "./components/AssessmentHistory";
import ReportViewer from "./components/ReportViewer";
import PrintableReport from "./PrintableReport";
import { usePrintReport } from "./hooks/usePrintReport";

import styles from "./ReportsPage.module.css";

export default function ReportsPage() {
  const { current, latestAssessment, history, hasAssessment, isLoading, selectAssessment } =
    useAssessment();
  const navigate = useNavigate();
  const [showNoAssessment, setShowNoAssessment] = useState(false);

  /** The report to print: the one currently being viewed, falling back to the latest. */
  const printable = current ?? latestAssessment;
  const { printRef, handlePrint, isPrinting } = usePrintReport(printable);

  const handlePrintReport = () => {
    soundService.play("click");
    if (printable) {
      handlePrint();
    } else {
      setShowNoAssessment(true);
    }
  };

  return (
    <div className={styles.page}>
      <motion.header
        className={styles.hero}
        initial={{ opacity: 0, y: 20 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ duration: 0.6, ease: [0.22, 1, 0.36, 1] }}
      >
        <div className={styles.heroBody}>
          <div className={styles.eyebrow}>
            <span className={styles.eyebrowIcon}>
              <FileText size={14} />
            </span>
            Clinical Reporting
          </div>
          <h1>Assessment Reports</h1>
          <p>
            View and analyze clinical risk assessment reports generated by the
            Random Forest model. Select any report from history to view its
            complete details, or print the latest completed assessment.
          </p>
        </div>
      </motion.header>

      <div className={styles.grid}>
        <div className={styles.left}>
          <AssessmentHistory
            history={history}
            current={current}
            isLoading={isLoading}
            onSelect={selectAssessment}
            onPrintLatest={handlePrintReport}
            isPrinting={isPrinting}
          />
        </div>

        <div className={styles.right}>
          {!hasAssessment ? (
            <AssessmentPromo
              title="No reports available."
              message="Complete an Assessment to generate your first cardiovascular risk report."
              buttonLabel="Start Assessment"
            />
          ) : current ? (
            <ReportViewer assessment={current} />
          ) : (
            <motion.div
              className={styles.empty}
              initial={{ opacity: 0, y: 14 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.5, ease: [0.22, 1, 0.36, 1] }}
            >
              <Stethoscope size={40} className={styles.emptyIcon} />
              <h2>No report selected</h2>
              <p>
                Run a new assessment to generate a clinical report, or select an
                existing one from the history panel.
              </p>
              <Link to="/assessment">
                <Button variant="primary" size="lg">
                  Run an Assessment
                </Button>
              </Link>
            </motion.div>
          )}
        </div>
      </div>

      {printable && <PrintableReport ref={printRef} assessment={printable} />}

      <AnimatePresence>
        {showNoAssessment && (
          <motion.div
            className={styles.modalBackdrop}
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            exit={{ opacity: 0 }}
            onClick={() => setShowNoAssessment(false)}
          >
            <motion.div
              role="dialog"
              aria-modal="true"
              aria-labelledby="no-assessment-title"
              className={styles.modal}
              initial={{ opacity: 0, scale: 0.95, y: 12 }}
              animate={{ opacity: 1, scale: 1, y: 0 }}
              exit={{ opacity: 0, scale: 0.95, y: 12 }}
              transition={{ duration: 0.25, ease: [0.22, 1, 0.36, 1] }}
              onClick={(event) => event.stopPropagation()}
            >
              <button
                type="button"
                className={styles.modalClose}
                aria-label="Close"
                onClick={() => setShowNoAssessment(false)}
              >
                <X size={18} />
              </button>
              <div className={styles.modalIcon}>
                <Stethoscope size={22} />
              </div>
              <h2 id="no-assessment-title">No Assessment Available</h2>
              <p>
                Please complete a cardiovascular risk assessment before printing
                a report.
              </p>
              <div className={styles.modalActions}>
                <Button
                  variant="primary"
                  size="lg"
                  onClick={() => {
                    setShowNoAssessment(false);
                    navigate("/assessment");
                  }}
                >
                  Go to Assessment
                </Button>
                <Button
                  variant="ghost"
                  size="lg"
                  onClick={() => setShowNoAssessment(false)}
                >
                  Close
                </Button>
              </div>
            </motion.div>
          </motion.div>
        )}
      </AnimatePresence>
    </div>
  );
}
