"""Feature contract — the single source of truth shared by the entire app.

The contract (`feature_contract.json` at the repository root) defines the exact
44 features, their order (== ``Random_Forest_Model.pkl.feature_names_in_``),
value ranges, and categorical encodings that the production model was trained
on. Every layer — the wizard, the API input schema, the feature mapper, and the
report — is derived from it so the model always receives real, in-distribution
values and never fabricated ones.

Generated by ``backend/scripts/build_feature_contract.py``. Do not hand-edit;
regenerate instead.
"""

import json
from functools import lru_cache
from pathlib import Path

from app.core.config import CONTRACT_PATH


class FeatureContractError(RuntimeError):
    """Raised when the contract is missing or inconsistent with the model."""


@lru_cache(maxsize=1)
def load_contract() -> dict:
    """Load and cache the canonical feature contract."""
    path = Path(CONTRACT_PATH)
    if not path.is_file():
        raise FeatureContractError(f"Feature contract not found: {path}")
    with open(path, encoding="utf-8") as fh:
        return json.load(fh)


def feature_order() -> list[str]:
    """The authoritative 44-feature order (== model.feature_names_in_)."""
    return list(load_contract()["feature_order"])


def categories() -> list[dict]:
    """The wizard's category sections with their ordered feature names."""
    contract = load_contract()
    mapping = contract["categories"]
    by_cat: dict[str, list[str]] = {key: [] for key in mapping}
    for feat in contract["features"]:
        by_cat[feat["category"]].append(feat["name"])

    return [
        {"id": key, "name": name, "features": by_cat[key]}
        for key, name in mapping.items()
    ]


def validate_against_model(model) -> None:
    """Assert the contract order matches the loaded model's training features."""
    expected = feature_order()
    actual = list(getattr(model, "feature_names_in_", expected))
    if actual != expected:
        raise FeatureContractError(
            "Contract/model mismatch: contract has %d features in order %s, "
            "model expects %d in order %s." % (len(expected), expected, len(actual), actual)
        )